require 'rake/packagetask'
require 'rubygems/tasks'

Gem::Tasks.new(
  :build => {:gem => true},
  :sign => {:checksum => true, :pgp => true}
)

desc "Make firefox extension"
task :fire do
  directory = '../firefox_driver/'
  zipfile_name = 'lib/pudi/pudi.xpi'
  File.delete(zipfile_name) if File.exists? zipfile_name
  require 'zip'
  Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
    Dir[File.join(directory, '**', '**')].each do |file|
      zipfile.add(file.sub(directory, ''), file)
    end
  end
end

task :default => [:fire,:build]
